# pyright: reportExplicitAny=false
"""Type stubs for ``tortoise.filters`` (local overlay).

Full replacement: the local ``stubs`` overlay REPLACES the upstream stubs and
the runtime analysis entirely (``stubPath`` overrides do not merge), so this
file must be self-sufficient and mirror the runtime module surface. It declares
every runtime export of ``tortoise/filters.py`` (encoders, filter operators,
and filter resolvers) plus the surface ``tortoise_extended`` patches at import
time (``get_filters_for_field`` and the ``_tortoise_extended_patched`` flag).

``Any`` is used where the runtime is untyped/dynamic (pypika terms, field
encoders). reportExplicitAny is disabled for this file for that reason.
"""

import operator as operator
from collections.abc import Callable, Iterable, Sequence
from typing import Any, NotRequired, TypedDict, override

from pypika_tortoise.queries import Table
from pypika_tortoise.terms import BasicCriterion, Criterion, Term
from tortoise.fields import Field
from tortoise.fields.relational import BackwardFKRelation, ManyToManyFieldInstance
from tortoise.models import Model

class FilterInfoDict(TypedDict):
    field: str
    operator: Callable[..., Any]
    backward_key: NotRequired[str]
    table: NotRequired[Table]
    value_encoder: NotRequired[Callable[..., Any]]
    source_field: NotRequired[str]
    is_tsvector: NotRequired[bool]

class Like(BasicCriterion):
    """A LIKE criterion that supports an ESCAPE clause."""

    escape: str

    def __init__(
        self, left: Any, right: Any, alias: Any = None, escape: str = " ESCAPE '\\'"
    ) -> None: ...
    @override
    def get_sql(self, ctx: Any) -> Any: ...

def escape_like(val: str) -> str: ...

# ── Encoders ────────────────────────────────────────────────────────────

def list_encoder(
    values: Iterable[Any], instance: Model, field: Field[object]
) -> list[Any]: ...
def related_list_encoder(
    values: Iterable[Any], instance: Model, field: Field[object]
) -> list[Any]: ...
def bool_encoder(value: Any, instance: Model, field: Field[object]) -> bool: ...
def string_encoder(value: Any, instance: Model, field: Field[object]) -> str: ...
def int_encoder(value: Any, instance: Model, field: Field[object]) -> int: ...
def json_encoder(
    value: Any, instance: Model, field: Field[object]
) -> dict[Any, Any]: ...
def array_encoder(
    value: Any | Sequence[Any], instance: Model, field: Field[object]
) -> Any: ...

# ── Operators ───────────────────────────────────────────────────────────

def is_in(field: Term, value: Any) -> Criterion: ...
def not_in(field: Term, value: Any) -> Criterion: ...
def between_and(field: Term, value: tuple[Any, Any]) -> Criterion: ...
def not_equal(field: Term, value: Any) -> Criterion: ...
def is_null(field: Term, value: Any) -> Criterion: ...
def not_null(field: Term, value: Any) -> Criterion: ...
def contains(field: Term, value: str) -> Criterion: ...
def search(field: Term, value: str) -> Any: ...
def posix_regex(field: Term, value: str) -> Any: ...
def insensitive_posix_regex(field: Term, value: str) -> Any: ...
def starts_with(field: Term, value: str) -> Criterion: ...
def ends_with(field: Term, value: str) -> Criterion: ...
def insensitive_exact(field: Term, value: str) -> Criterion: ...
def insensitive_contains(field: Term, value: str) -> Criterion: ...
def insensitive_starts_with(field: Term, value: str) -> Criterion: ...
def insensitive_ends_with(field: Term, value: str) -> Criterion: ...
def extract_year_equal(field: Term, value: int) -> Criterion: ...
def extract_quarter_equal(field: Term, value: int) -> Criterion: ...
def extract_month_equal(field: Term, value: int) -> Criterion: ...
def extract_week_equal(field: Term, value: int) -> Criterion: ...
def extract_day_equal(field: Term, value: int) -> Criterion: ...
def extract_hour_equal(field: Term, value: int) -> Criterion: ...
def extract_minute_equal(field: Term, value: int) -> Criterion: ...
def extract_second_equal(field: Term, value: int) -> Criterion: ...
def extract_microsecond_equal(field: Term, value: int) -> Criterion: ...
def json_contains(field: Term, value: str) -> Criterion: ...
def json_contained_by(field: Term, value: str) -> Criterion: ...
def json_filter(field: Term, value: dict[Any, Any]) -> Criterion: ...
def array_contains(field: Term, value: Any | Sequence[Any]) -> Criterion: ...
def array_contained_by(field: Term, value: Any | Sequence[Any]) -> Criterion: ...
def array_overlap(field: Term, value: Any | Sequence[Any]) -> Criterion: ...
def array_length(field: Term, value: int) -> Criterion: ...

# ── Filter resolvers ────────────────────────────────────────────────────

def get_m2m_filters(
    field_name: str, field: ManyToManyFieldInstance[Any]
) -> dict[str, FilterInfoDict]: ...
def get_backward_fk_filters(
    field_name: str, field: BackwardFKRelation[Any]
) -> dict[str, FilterInfoDict]: ...
def get_json_filter(
    field_name: str, source_field: str
) -> dict[str, FilterInfoDict]: ...
def get_array_filter(
    field_name: str, source_field: str, field: Field[object]
) -> dict[str, FilterInfoDict]: ...
def get_filters_for_field(
    field_name: str, field: Field[object] | None, source_field: str
) -> dict[str, FilterInfoDict]: ...

_tortoise_extended_patched: bool
