"""Partial type stubs for aiodocker.

Only covers the subset of the API used by css_mcp.  The upstream
package ships ``py.typed`` but its inline annotations contain many
``Unknown`` types that trigger ``reportUnknownMemberType`` in strict
mode.  These stubs narrow the signatures to concrete types.
"""

from collections.abc import AsyncIterator, Coroutine, Mapping, MutableMapping, Sequence
from typing import Protocol, TypeVar

_T_co = TypeVar("_T_co", covariant=True)

class SupportsRead(Protocol[_T_co]):
    def read(self, length: int = ..., /) -> _T_co: ...


class Docker:
    def __init__(
        self,
        url: str | None = ...,
        *,
        timeout: int | None = ...,
    ) -> None: ...
    @property
    def containers(self) -> DockerContainers: ...
    @property
    def images(self) -> DockerImages: ...
    @property
    def volumes(self) -> DockerVolumes: ...
    @property
    def networks(self) -> DockerNetworks: ...
    @property
    def services(self) -> DockerServices: ...
    async def close(self) -> None: ...

class DockerContainers:
    async def get(self, container_id: str) -> DockerContainer: ...
    async def list(self, **kwargs: str) -> list[DockerContainer]: ...
    async def create(
        self,
        config: dict[str, object],
        *,
        name: str | None = ...,
    ) -> DockerContainer: ...
    async def create_or_replace(
        self,
        name: str,
        config: dict[str, object],
    ) -> DockerContainer: ...

class DockerContainer:
    @property
    def id(self) -> str: ...
    async def show(self) -> dict[str, object]: ...
    async def start(self) -> None: ...
    async def stop(self, *, t: int | None = ...) -> None: ...
    async def delete(self, *, force: bool = ..., v: bool = ..., link: bool = ...) -> None: ...
    async def restart(self, *, t: int | None = ...) -> None: ...
    async def kill(self, *, signal: str | None = ...) -> None: ...
    async def rename(self, newname: str) -> None: ...
    async def pause(self) -> None: ...
    async def unpause(self) -> None: ...
    async def wait(self) -> dict[str, object]: ...
    def log(
        self,
        *,
        stdout: bool = ...,
        stderr: bool = ...,
        follow: bool = ...,
    ) -> AsyncIterator[str]: ...

class DockerImages:
    def build(
        self,
        *,
        remote: str | None = ...,
        fileobj: SupportsRead[bytes] | None = ...,
        path_dockerfile: str | None = ...,
        tag: str | None = ...,
        quiet: bool = ...,
        nocache: bool = ...,
        buildargs: Mapping[str, str] | None = ...,
        pull: bool = ...,
        rm: bool = ...,
        forcerm: bool = ...,
        labels: Mapping[str, str] | None = ...,
        platform: str | None = ...,
        stream: bool = ...,
        encoding: str | None = ...,
    ) -> Coroutine[object, object, list[dict[str, object]]]: ...
    async def get(self, name: str) -> DockerImage: ...
    async def pull(self, name: str, *, tag: str | None = ...) -> DockerImage: ...

class DockerImage:
    @property
    def id(self) -> str: ...
    async def show(self) -> dict[str, object]: ...

class DockerVolumes:
    async def create(self, config: dict[str, object]) -> DockerVolume: ...
    async def get(self, name: str) -> DockerVolume: ...
    async def list(self, *, filters: Mapping[str, Sequence[str]] | None = ...) -> dict[str, object]: ...

class DockerVolume:
    @property
    def name(self) -> str: ...
    async def show(self) -> dict[str, object]: ...
    async def delete(self) -> None: ...

class DockerNetworks:
    async def create(self, name: str, **kwargs: str) -> DockerNetwork: ...
    async def get(self, name: str) -> DockerNetwork: ...
    async def list(self, **kwargs: str) -> list[DockerNetwork]: ...

class DockerNetwork:
    async def show(self) -> dict[str, object]: ...
    async def connect(self, container_id: str) -> None: ...
    async def disconnect(self, container_id: str) -> None: ...
    async def delete(self) -> None: ...

class DockerServices:
    async def create(
        self,
        task_template: Mapping[str, object],
        *,
        name: str | None = ...,
        labels: Mapping[str, str] | None = ...,
        mode: Mapping[str, object] | None = ...,
        update_config: Mapping[str, object] | None = ...,
        rollback_config: Mapping[str, object] | None = ...,
        networks: Sequence[Mapping[str, object]] | None = ...,
        endpoint_spec: Mapping[str, object] | None = ...,
        auth: MutableMapping[str, str] | str | bytes | None = ...,
        registry: str | None = ...,
    ) -> dict[str, object]: ...
    async def inspect(self, service_id: str) -> dict[str, object]: ...
    async def list(self, *, filters: Mapping[str, Sequence[str]] | None = ...) -> list[dict[str, object]]: ...
    async def update(
        self,
        service_id: str,
        version: str,
        *,
        image: str | None = ...,
        rollback: bool = ...,
    ) -> bool: ...
    async def delete(self, service_id: str) -> bool: ...
